version: '3.9'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: messages
    ports:
      - "5420:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  migrate:
    image: migrate/migrate
    entrypoint: [ "/bin/sh", "-c", "while ! pg_isready -h postgres -p 5432 -U user; do sleep 1; done; migrate -path /migrations -database postgres://postgres:123321@postgres:5420/messages?sslmode=disable up" ]
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
    environment:
      - DATABASE_URLA=postgres://postgres:123321@localhost:5420/messages
      - KAFKA_URL=kafka:9092
      - KAFKA_TOPIC=message
      - migrate

volumes:
  postgres-data:
