CREATE TABLE messages (
                          id int8 generated by default as identity PRIMARY KEY,
                          content TEXT NOT NULL,
                          processed BOOLEAN DEFAULT FALSE
);
